### ISSUE TITLE
I doubt that this is not a mini book on Promise.

### ISSUE THREAD

**Issue by miniroadrunner** [azu/promises-book#282] opened 2017-08-04 09:06 UTC
This mini book is not mini, it takes too long pages to describe the Promise, the new feature in ES6.

**Comment by azu** [comment] 2017-08-04 09:22
> JavaScript Promiseについての薄い電子書籍です。

We hadn't said mini.

Duplicate of #280

**Closed by azu** 2017-08-04 09:22 UTC
Labels: duplicate

**Comment by miniroadrunner** [comment] 2017-08-10 06:01
yes? I am Chinese. I read your book in Chinese Edition (Chinese: JavaScript Promise迷你书（中文版）). And the Chinese "迷你" in English is mini. Why name this book "迷你书" in Chinese ?
